#!/bin/sh

VERSION=`python -c "from version import appversion; print '%4.2f' % appversion"`
VER=`python -c "from version import appversion; print int(round(appversion*100,0))"`
APPNAME=`python -c "from version import appname; print appname"`
APPLINUX=`python -c "from version import appname; print appname.lower()"`
RELEASE=1

rm -f ${APPNAME}_${VER}_src.zip
rm -f ${APPLINUX}-$VERSION-$RELEASE.noarch.rpm
rm -f ${APPLINUX}_$VERSION-$RELEASE_all.deb
rm -f ${APPNAME}_${VER}_mac.zip
rm -rf ${APPNAME}.app

PY='fs2xp.py FS2XPlane.py convatc.py convbgl.py convmain.py convmdl.py convobjs.py convphoto.py convtaxi.py convutil.py convxml.py MessageBox.py version.py'
RSRC=`ls Resources/*.{bgl,dds,fac,for,html,lin,obj,png,pol,txt,xml}`
HELP='DSFTool bglunzip bglxml bmp2dds bmp2png fake2004 winever'

# linux
RPM=/tmp/${APPLINUX}
RPMRT=$RPM/root
rm -rf $RPM
mkdir -p $RPM/BUILD
mkdir -p $RPM/SOURCES
mkdir -p $RPM/SPECS
mkdir -p $RPM/RPMS/noarch
mkdir -p $RPMRT/usr/local/bin
mkdir -p $RPMRT/usr/local/lib/${APPLINUX}/Resources
mkdir -p $RPMRT/usr/local/lib/${APPLINUX}/linux
mkdir -p $RPMRT/usr/local/lib/${APPLINUX}/win32
mkdir -p $RPMRT/usr/local/share/applications
mkdir -p $RPMRT/usr/local/share/icons/hicolor/48x48/apps
mkdir -p $RPMRT/usr/local/share/icons/hicolor/128x128/apps
cp -p linux/${APPLINUX}.spec $RPM/SPECS/
cp -p linux/fs2xp $RPMRT/usr/local/bin/
cp -p linux/${APPLINUX} $RPMRT/usr/local/bin/
cp -p linux/${APPLINUX}.desktop $RPMRT/usr/local/share/applications/
cp -p Resources/${APPNAME}.png $RPMRT/usr/local/share/icons/hicolor/48x48/apps/${APPLINUX}.png
cp -p linux/${APPNAME}-128.png $RPMRT/usr/local/share/icons/hicolor/128x128/apps/${APPLINUX}.png
cp -p linux/${APPNAME}-128.png $RPMRT/usr/local/lib/${APPLINUX}/Resources/
for i in $PY; do cp -p "$i" $RPMRT/usr/local/lib/${APPLINUX}/; done
for i in $RSRC; do cp -p "$i" $RPMRT/usr/local/lib/${APPLINUX}/Resources/; done
for i in $HELP; do cp -p "linux/$i" $RPMRT/usr/local/lib/${APPLINUX}/linux/; done
for i in win32/bglunzip.exe win32/fake2004.exe; do cp -p "$i" $RPMRT/usr/local/lib/${APPLINUX}/win32/; done
rpmbuild -bb --buildroot $RPMRT --define "_target_os linux" --define "_target_vendor pc" --define "_topdir $RPM" --define "_unpackaged_files_terminate_build 0" --define "version $VERSION" --define "release $RELEASE" --quiet $RPM/SPECS/${APPLINUX}.spec
mv $RPM/RPMS/noarch/${APPLINUX}-$VERSION-$RELEASE.noarch.rpm .

# Debian/Ubuntu
mkdir -p $RPMRT/DEBIAN
echo Version: $VERSION-$RELEASE> $RPMRT/DEBIAN/control
cat   linux/control >> $RPMRT/DEBIAN/control
cp -p linux/postinst $RPMRT/DEBIAN/
mkdir -p $RPMRT/usr/local/share/doc/${APPLINUX}/
cp -p linux/copyright  $RPMRT/usr/local/share/doc/${APPLINUX}/
fakeroot "dpkg-deb -b $RPMRT ."	# requires gnu-tar

# mac
mkdir -p ${APPNAME}.app/Contents
sed s/appversion/${VERSION}/ <MacOS/Info.plist >${APPNAME}.app/Contents/Info.plist
mkdir -p ${APPNAME}.app/Contents/MacOS
cp -p MacOS/${APPNAME} ${APPNAME}.app/Contents/MacOS/
for i in $PY; do cp -p "$i" ${APPNAME}.app/Contents/MacOS/; done
for i in $HELP; do cp -p "MacOS/$i" ${APPNAME}.app/Contents/MacOS/; done
mkdir -p ${APPNAME}.app/Contents/MacOS/win32
for i in win32/bglunzip.exe win32/fake2004.exe; do cp -p "$i" ${APPNAME}.app/Contents/MacOS/win32/; done
mkdir -p ${APPNAME}.app/Contents/Resources
for i in $RSRC; do cp -p "$i" ${APPNAME}.app/Contents/Resources/; done
cp -p MacOS/*.icns MacOS/*.png ${APPNAME}.app/Contents/Resources/	# overwrite with Mac versions
python2.5 -OO ./bundledeps.py -x wx -o ${APPNAME}.app ${APPNAME}.py	# exclude wx - included with 10.5 and 10.6
python2.7 -OO ./bundledeps.py -o ${APPNAME}.app ${APPNAME}.py
codesign --deep -s "Developer ID Application: Jonathan Harris" ${APPNAME}.app
ditto -ck --keepParent --sequesterRsrc ${APPNAME}.app ${APPNAME}_${VER}_mac.zip
