#!/bin/bash

# Find lsregister
LS=/System/Library/Frameworks/ApplicationServices.framework/Frameworks/LaunchServices.framework/Support/lsregister;
if [ ! -x $LS ] ;then
    echo Can\'t find the lsregister tool!
    exit 1;
fi

# Candidate application locations
WINES=$($LS -dump | awk 'match($0, "/.*/Wine.bundle") { print substr($0, RSTART) "/Contents/bin/wine" }' | sort -u)
for I in $WINES; do
    if [ -x "$I" ]; then
	export WINELOADER="$I"
	break;
    fi;
done
if [ ! "$WINELOADER" ]; then
    echo Can\'t find wine!
    exit 1;
fi

unset DISPLAY
export WINESERVER="${WINELOADER}server"
"$WINELOADER" ./MacOS/win32/bglunzip.exe "$1" "$2"
