#!/bin/bash

IFS='
'

LS=/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/Support/lsregister	# MacOS 10.5
if [ ! -x $LS ]; then
    # From http://developer.apple.com/documentation/Carbon/Conceptual/MDImporters/Concepts/Troubleshooting.html
    LS=/System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/Support/lsregister	# MacOS 10.3 & 10.4
    if [ ! -x $LS ]; then
        echo Can\'t find the lsregister tool!
        exit 1;
    fi;
fi

# Candidate application locations
for I in $($LS -dump | grep -v .Trash | grep -oE "/.+/CrossOver.*\.app" | sort -u); do
	if [ -d "$I" ]; then
		for J in $(find "$I" -type f -name wineloader); do
			if [ -x "$J" ]; then
				export WINELOADER="$J"
				break 2;
			fi;
		done;
	fi;
done

if [ ! "$WINELOADER" ]; then
	for I in $($LS -dump | grep -v .Trash | grep -oE "/.+/Wine\.app" | sort -u); do
		if [ -x "$I/Contents/Resources/bin/wine" ]; then
			export WINELOADER="$I/Contents/Resources/bin/wine"
			break;
		fi;
	done;
fi;

if [ ! "$WINELOADER" ]; then
	echo Not installed
	exit 1;
fi

# Make a default bottle
for I in $(find ~/Library/Application\ Support -type d -name "CrossOver*" | sort); do
	if [ -d "$I/Bottles" ]; then
		if [ -a "$I/Bottles/default" ]; then
			WINEPREFIX="$I/Bottles/default"
			break;
		else
			for J in $(find "$I/Bottles" -type d -depth 1); do
				WINEPREFIX="$I/Bottles/default"
				ln -s "$J" $WINEPREFIX
				break 2;
			done;
		fi
	fi;
done;

if [ ! "$WINEPREFIX" ]; then
	WINEPREFIX=~/.wine;
fi

unset DISPLAY
export WINEPREFIX
"$WINELOADER" ./MacOS/win32/fake2004.exe

# Link fake 2004 into default bottle
if [ -e "$WINEPREFIX/dosdevices/c:/Program Files" ]; then
	if [ ! -e "$WINEPREFIX/dosdevices/c:/Program Files/Microsoft Games/Flight Simulator 9" ]; then
		mkdir -p "$WINEPREFIX/dosdevices/c:/Program Files/Microsoft Games"
		ln -s ~/FS2004 "$WINEPREFIX/dosdevices/c:/Program Files/Microsoft Games/Flight Simulator 9";
	fi
	if [ ! -e "$WINEPREFIX/dosdevices/c:/Program Files/Microsoft Games/Microsoft Flight Simulator X" ]; then
		mkdir -p "$WINEPREFIX/dosdevices/c:/Program Files/Microsoft Games"
		ln -s ~/FS2004 "$WINEPREFIX/dosdevices/c:/Program Files/Microsoft Games/Microsoft Flight Simulator X";
		touch ~/FS2004/fsx.exe;	# may not exist if upgrading
    fi;
fi
