#!/bin/bash

LS=/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/Support/lsregister	# MacOS 10.5
if [ ! -x $LS ]; then
    # From http://developer.apple.com/documentation/Carbon/Conceptual/MDImporters/Concepts/Troubleshooting.html
    LS=/System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/Support/lsregister	# MacOS 10.3 & 10.4
    if [ ! -x $LS ]; then
        echo Can\'t find the lsregister tool!
        exit 1;
    fi;
fi

# Candidate application locations
WINES=$($LS -dump | awk '!match($0, "\.Trash") && match($0, "/.*/CrossOver.*\.app$") { print substr($0, RSTART) "/Contents/SharedSupport/CrossOver/bin/wine" }' | sort -u)
for I in $WINES; do
    if [ -x "$I" ]; then
	export WINELOADER="$I"
	break;
    fi;
done
if [ ! "$WINELOADER" ]; then
    WINES=$($LS -dump | awk '!match($0, "\.Trash") && match($0, "/.*/Wine\.bundle") { print substr($0, RSTART) "/Contents/bin/wine" }' | sort -u)
    for I in $WINES; do
	if [ -x "$I" ]; then
	    export WINELOADER="$I"
	    break;
	fi;
    done
    if [ ! "$WINELOADER" ]; then
	echo Not installed
	exit 1;
    fi;
fi

unset DISPLAY
export WINESERVER="${WINELOADER}server"
"$WINELOADER" ./MacOS/win32/fake2004.exe

if [ -e ~/Library/Application\ Support/CrossOver/Bottles/default/dosdevices/c:/Program\ Files ]; then
    if [ ! -e ~/Library/Application\ Support/CrossOver/Bottles/default/dosdevices/c:/Program\ Files/Microsoft\ Games/Flight\ Simulator\ 9 ]; then
	mkdir -p ~/Library/Application\ Support/CrossOver/Bottles/default/dosdevices/c:/Program\ Files/Microsoft\ Games
	ln -s ~/FS2004  ~/Library/Application\ Support/CrossOver/Bottles/default/dosdevices/c:/Program\ Files/Microsoft\ Games/Flight\ Simulator\ 9;
    fi
    if [ ! -e ~/Library/Application\ Support/CrossOver/Bottles/default/dosdevices/c:/Program\ Files/Microsoft\ Games/Microsoft\ Flight\ Simulator\ X ]; then
	mkdir -p ~/Library/Application\ Support/CrossOver/Bottles/default/dosdevices/c:/Program\ Files/Microsoft\ Games
	ln -s ~/FS2004  ~/Library/Application\ Support/CrossOver/Bottles/default/dosdevices/c:/Program\ Files/Microsoft\ Games/Microsoft\ Flight\ Simulator\ X
	touch ~/FS2004/fsx.exe;	# may not exist if upgrading
    fi;
fi
if [ -e  ~/Library/Application\ Support/CrossOver/Bottles/default/dosdevices/c:/windows/profiles/All\ Users/Application\ Data ] && [ ! -e ~/FS2004 ~/Library/Application\ Support/CrossOver/Bottles/default/dosdevices/c:/windows/profiles/All\ Users/Application\ Data/Microsoft/FSX ]; then
    mkdir -p ~/Library/Application\ Support/CrossOver/Bottles/default/dosdevices/c:/windows/profiles/All\ Users/Application\ Data/Microsoft
    ln -s ~/FS2004 ~/Library/Application\ Support/CrossOver/Bottles/default/dosdevices/c:/windows/profiles/All\ Users/Application\ Data/Microsoft/FSX;
fi

if [ -e ~/.wine/dosdevices/c:/Program\ Files ]; then
    if [ ! -e ~/.wine/dosdevices/c:/Program\ Files/Microsoft\ Games/Flight\ Simulator\ 9 ]; then
	mkdir -p ~/.wine/dosdevices/c:/Program\ Files/Microsoft\ Games
	ln -s ~/FS2004  ~/.wine/dosdevices/c:/Program\ Files/Microsoft\ Games/Flight\ Simulator\ 9;
    fi
    if [ ! -e ~/.wine/dosdevices/c:/Program\ Files/Microsoft\ Games/Microsoft\ Flight\ Simulator\ X ]; then
	mkdir -p ~/.wine/dosdevices/c:/Program\ Files/Microsoft\ Games
	ln -s ~/FS2004  ~/.wine/dosdevices/c:/Program\ Files/Microsoft\ Games/Microsoft\ Flight\ Simulator\ X
	touch ~/FS2004/fsx.exe;	# may not exist if upgrading
    fi;
fi
if [ -e ~/.wine/dosdevices/c:/windows/profiles/All\ Users/Application\ Data ] && [ ! -e ~/.wine/dosdevices/c:/windows/profiles/All\ Users/Application\ Data/Microsoft/FSX ]; then
    mkdir -p ~/.wine/dosdevices/c:/windows/profiles/All\ Users/Application\ Data/Microsoft
    ln -s ~/FS2004 ~/.wine/dosdevices/c:/windows/profiles/All\ Users/Application\ Data/Microsoft/FSX;
fi
