#!/bin/sh
# Actually executed by user's default shell (ignoring previous line), so don't do anything fancy

# Force default Python so picks up system wxPython
exec /bin/bash -s<<EOF
cd $(dirname $0)
if [[ $(sw_vers -productVersion) < 10.5 ]]; then
    /usr/bin/pythonw2.3 -OO "$(basename $0).py";
else
    /usr/bin/pythonw2.5 -OO "$(basename $0).py";
fi
EOF
