#!/bin/bash

IFS='
'

LS=/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/Support/lsregister	# MacOS 10.5
if [ ! -x $LS ]; then
	# From http://developer.apple.com/documentation/Carbon/Conceptual/MDImporters/Concepts/Troubleshooting.html
	LS=/System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/Support/lsregister	# MacOS 10.3 & 10.4
	if [ ! -x $LS ]; then
		echo Can\'t find the lsregister tool!
		exit 1;
	fi;
fi

# Candidate application locations
for I in $($LS -dump | grep -v .Trash | grep -oE "/.+/CrossOver.*\.app" | sort -u); do
	if [ -d "$I" ]; then
		for J in $(find "$I" -type f -name wineloader); do
			if [ -x "$J" ]; then
				export WINELOADER="$J"
				break 2;
			fi;
		done;
	fi;
done

if [ ! "$WINELOADER" ]; then
	for I in $($LS -dump | grep -v .Trash | grep -oE "/.+/Wine\.app" | sort -u); do
		if [ -x "$I/Contents/Resources/bin/wine" ]; then
			export WINELOADER="$I/Contents/Resources/bin/wine"
			break;
		fi;
	done;
fi;

if [ ! "$WINELOADER" ]; then
	echo Not installed
	exit 1;
fi

unset DISPLAY
"$WINELOADER" --version
