#!/bin/sh

wine ./win32/fake2004.exe
if [ ! -e ~/.wine/dosdevices/c:/Program\ Files/Microsoft\ Games ]; then
    mkdir -p ~/.wine/dosdevices/c:/Program\ Files/Microsoft\ Games
    ln -s ~/FS2004  ~/.wine/dosdevices/c:/Program\ Files/Microsoft\ Games/Flight\ Simulator\ 9;
fi
