#!/bin/sh

wine ./win32/fake2004.exe

if [ -e ~/.wine/dosdevices/c:/Program\ Files ]; then
	if [ ! -e ~/.wine/dosdevices/c:/Program\ Files/Microsoft\ Games/Flight\ Simulator\ 9 ]; then
		mkdir -p ~/.wine/dosdevices/c:/Program\ Files/Microsoft\ Games
		ln -s ~/FS2004  ~/.wine/dosdevices/c:/Program\ Files/Microsoft\ Games/Flight\ Simulator\ 9;
	fi
	if [ ! -e ~/.wine/dosdevices/c:/Program\ Files/Microsoft\ Games/Microsoft\ Flight\ Simulator\ X ]; then
		mkdir -p ~/.wine/dosdevices/c:/Program\ Files/Microsoft\ Games
		ln -s ~/FS2004  ~/.wine/dosdevices/c:/Program\ Files/Microsoft\ Games/Microsoft\ Flight\ Simulator\ X
		touch ~/FS2004/fsx.exe;	# may not exist if upgrading
	fi;
fi
